Repository navimakarov/LaplaceRedux.jl, pull requests merged in 2023-06, with the labels that each got.

#24 Implemented GGN
  dev/ggn/GGN-Julia.ipynb
  dev/ggn/GGN-Python.ipynb
  dev/ggn/data1.csv
  src/curvature/functions.jl
  src/laplace.jl
  test/Project.toml
  test/laplace.jl
Labels: planned feature, must

#33 Pipeline improvements
  .github/workflows/CI.yml
  test/benchmarks/BenchmarkFit.jl
Labels: could, non-functional

#39 Attempt to fix error
  .github/workflows/CI.yml
  benchmarks/BenchmarkFit.jl
Labels: bug
